# Generated by Django 6.1 on 2026-09-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
                ('award', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('field', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
