# Generated by Django 6.1 on 2026-09-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.achievement')),
            ],
        ),
    ]
